#!/bin/bash
# Script to deploy CycleStreets dev server on Ubuntu
# Written for Ubuntu Server 26.04 LTS (View Ubuntu version using 'lsb_release -a')
# This script is idempotent - it can be safely re-run without destroying existing data

echo "#	CycleStreets Dev machine deployment $(date)"

# Ensure this script is run as root
if [ "$(id -u)" != "0" ]; then
    echo "#	This script must be run as root." 1>&2
    exit 1
fi

# Bomb out if something goes wrong
set -e


### CREDENTIALS ###

# Get the script directory see: https://stackoverflow.com/a/246128
# The second single line solution from that page is probably good enough as it is unlikely that this script itself will be symlinked.
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Use this to remove the ../
ScriptHome=$(readlink -f "${DIR}/..")

# Name of the credentials file
configFile=${ScriptHome}/.config.sh

# Generate your own credentials file by copying from .config.sh.template
if [ ! -x ${configFile} ]; then
    echo "#	The config file, ${configFile}, does not exist or is not executable - copy your own based on the ${configFile}.template file." 1>&2
    exit 1
fi

# Load the credentials
. ${configFile}

# Install a base webserver machine with webserver software (Apache, PHP, MySQL), relevant users and main directory
. ${ScriptHome}/utility/installBaseWebserver.sh

# Install PhpMyAdmin non-interactively; see: http://stackoverflow.com/questions/22440298/preseeding-phpmyadmin-skip-multiselect-skip-password
apt-get install -y pwgen
AUTOGENERATED_PASS=`pwgen -c -1 20`
echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections
echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-user string root" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-pass password $mysqlRootPassword" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/app-pass password $AUTOGENERATED_PASS" |debconf-set-selections
echo "phpmyadmin phpmyadmin/app-password-confirm password $AUTOGENERATED_PASS" | debconf-set-selections
apt-get -y install phpmyadmin
# Disable by default, as this will add to all VirtualHosts; instead, add the following to an Apache VirtualHost:
#  Include /etc/apache2/conf-available/phpmyadmin.conf
#  Alias / /usr/share/phpmyadmin/
a2disconf phpmyadmin
service apache2 reload

# Exim
# Mail Transfer Agent (MTA); NB load before Python otherwise Ubuntu will choose Postfix
# See: https://ubuntu.com/server/docs/how-to/mail-services/install-exim4/ and https://manpages.ubuntu.com/manpages/stonking/man8/update-exim4.conf.8.html
apt-get -y install exim4
if [ ! -e /etc/exim4/update-exim4.conf.conf.original ]; then
	# NB These will deliberately overwrite any existing config; it is assumed that once set, the config will only be changed via this setup script (as otherwise it is painful during testing)
	cp -pr /etc/exim4/update-exim4.conf.conf /etc/exim4/update-exim4.conf.conf.original
	sed -i "s/dc_eximconfig_configtype=.*/dc_eximconfig_configtype='internet'/" /etc/exim4/update-exim4.conf.conf	# Use 'internet' for direct delivery, or 'satellite' if mail is delivered by your ISP
	sed -i "s/dc_local_interfaces=.*/dc_local_interfaces=''/" /etc/exim4/update-exim4.conf.conf			# Use '' if using 'internet' or '127.0.0.1' if using 'satellite' above
	sed -i "s/dc_readhost=.*/dc_readhost='cyclestreets.net'/" /etc/exim4/update-exim4.conf.conf			# Set to 'cyclestreets.net'
	sed -i "s/dc_smarthost=.*/dc_smarthost=''/" /etc/exim4/update-exim4.conf.conf					# Use '' if using 'internet' or 'mx.yourispmailhost.com' if using 'satellite' above
fi
update-exim4.conf
service exim4 restart

# Mailman
cd ${ScriptHome}/install-dev/mailman2-python3/
./install-mailman.sh lists.cyclestreets.net 'webmaster'@'cyclestreets.net'
cd ../

# Wiki, using Wikimedia
apt-get update
apt-get install -y mediawiki
if [ ! -d /var/lib/mediawiki/extensions/Auth_remoteuser ]; then
	git clone https://github.com/wikimedia/mediawiki-extensions-Auth_remoteuser.git /var/lib/mediawiki/extensions/Auth_remoteuser
fi
if [ ! -f /etc/apache2/sites-available/wiki.conf ]; then
	# cp -pr ${ScriptHome}/dev-deployment/wiki-apache.conf /etc/apache2/sites-available/wiki.conf
fi
a2ensite wiki
service apache2 restart

# Add MySQL credentials
AUTOGENERATED_PASS=`pwgen -c -1 20`
echo "Using password: ${AUTOGENERATED_PASS}"
mysql -u root -p${mysqlRootPassword} -e "CREATE DATABASE IF NOT EXISTS wiki;"
mysql -u root -p${mysqlRootPassword} -e "CREATE USER 'wiki'@'localhost' IDENTIFIED BY '${AUTOGENERATED_PASS}';"
mysql -u root -p${mysqlRootPassword} -e "GRANT ALL PRIVILEGES ON wiki.* TO 'wiki'@'localhost' WITH GRANT OPTION;"
mysql -u root -p${mysqlRootPassword} -e "FLUSH PRIVILEGES;"

# Munin Server; see: https://www.digitalocean.com/community/tutorials/how-to-install-the-munin-monitoring-tool-on-ubuntu-14-04
apt-get install -y apache2-utils
apt-get install -y libcgi-fast-perl libapache2-mod-fcgid
a2enmod fcgid
apt-get install -y munin
chown -R munin:www-data /var/lib/munin/cgi-tmp/
chmod -R g+w /var/lib/munin/cgi-tmp/
# Disable by default, as this will add to all VirtualHosts; instead, add the following to an Apache VirtualHost:
#  Include /etc/apache2/conf-available/munin.conf
#  Alias / /var/cache/munin/www/
a2disconf munin
service apache2 reload

# Munin client
. ${ScriptHome}/utility/installMunin.sh

# Install firewall
. ${ScriptHome}/utility/installFirewall.sh

# Confirm end of script
echo -e "#	All now deployed $(date)"

# End of file
