#!/bin/bash
# Script to deploy CycleStreets dev server on Ubuntu
# Written for Ubuntu Server 16.04 LTS (View Ubuntu version using 'lsb_release -a')
# This script is idempotent - it can be safely re-run without destroying existing data

echo "#	CycleStreets Dev machine deployment $(date)"

# Ensure this script is run as root
if [ "$(id -u)" != "0" ]; then
    echo "#	This script must be run as root." 1>&2
    exit 1
fi

# Bomb out if something goes wrong
set -e

### CREDENTIALS ###

# Get the script directory see: http://stackoverflow.com/a/246128/180733
# The second single line solution from that page is probably good enough as it is unlikely that this script itself will be symlinked.
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Use this to remove the ../
ScriptHome=$(readlink -f "${DIR}/..")

# Name of the credentials file
configFile=${ScriptHome}/.config.sh

# Generate your own credentials file by copying from .config.sh.template
if [ ! -x ${configFile} ]; then
    echo "#	The config file, ${configFile}, does not exist or is not excutable - copy your own based on the ${configFile}.template file." 1>&2
    exit 1
fi

# Load the credentials
. ${configFile}

# Check a base OS has been defined
if [ -z "${baseOS}" ]; then
	echo "#     Please define a value for baseOS in the config file."
	exit 1
fi
echo "# Installing CycleStreets website for base OS: ${baseOS}"

# Install a base webserver machine with webserver software (Apache, PHP, MySQL), relevant users and main directory
. ${ScriptHome}/utility/installBaseWebserver.sh

# Enable mod_ssl for HTTPS sites
a2enmod ssl
service apache2 reload

# Add mod_macro to help simplify Apache configuration
apt-get -y install libapache2-mod-macro
a2enmod macro

# Install PhpMyAdmin non-interactively; see: http://stackoverflow.com/questions/22440298/preseeding-phpmyadmin-skip-multiselect-skip-password
apt-get install -y pwgen
AUTOGENERATED_PASS=`pwgen -c -1 20`
echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections
echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-user string root" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-pass password $mysqlRootPassword" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/app-pass password $AUTOGENERATED_PASS" |debconf-set-selections
echo "phpmyadmin phpmyadmin/app-password-confirm password $AUTOGENERATED_PASS" | debconf-set-selections
apt-get -y install phpmyadmin
phpenmod mcrypt
# Disable by default, as this will add to all VirtualHosts; instead, add the following to an Apache VirtualHost:
#  Include /etc/apache2/conf-available/phpmyadmin.conf
#  Alias / /usr/share/phpmyadmin/
a2disconf phpmyadmin
service apache2 reload

# Exim
# Mail Transfer Agent (MTA); NB load before Python otherwise Ubuntu will choose Postfix
# See: https://help.ubuntu.com/lts/serverguide/exim4.html and http://manpages.ubuntu.com/manpages/hardy/man8/update-exim4.conf.8.html
# NB The config here is currently Debian/Ubuntu-specific
apt-get -y install exim4
if [ ! -e /etc/exim4/update-exim4.conf.conf.original ]; then
	cp -pr /etc/exim4/update-exim4.conf.conf /etc/exim4/update-exim4.conf.conf.original
	# NB These will deliberately overwrite any existing config; it is assumed that once set, the config will only be changed via this setup script (as otherwise it is painful during testing)
	sed -i "s/dc_eximconfig_configtype=.*/dc_eximconfig_configtype='internet'/" /etc/exim4/update-exim4.conf.conf
	sed -i "s/dc_other_hostnames=.*/dc_other_hostnames='${dc_other_hostnames}'/" /etc/exim4/update-exim4.conf.conf
	sed -i "s/dc_local_interfaces=.*/dc_local_interfaces=''/" /etc/exim4/update-exim4.conf.conf
	sudo update-exim4.conf
	sudo service exim4 restart
fi

# Munin Server; see: https://www.digitalocean.com/community/tutorials/how-to-install-the-munin-monitoring-tool-on-ubuntu-14-04
apt-get install -y apache2-utils
apt-get install -y libcgi-fast-perl libapache2-mod-fcgid
a2enmod fcgid
apt-get install -y munin
# Disable by default, as this will add to all VirtualHosts; instead, add the following to an Apache VirtualHost:
#  Include /etc/apache2/conf-available/munin.conf
#  Alias / /var/cache/munin/www/
a2disconf munin
service apache2 reload

# Downloads area
. ${ScriptHome}/dev-deployment/install-downloads.sh

# Confirm end of script
echo -e "#	All now deployed $(date)"

# End of file
