#!/bin/bash
#	Used to restore viola from backups generated by olivia - when olivia is acting as the live machine
#	Uses output from the toViola script
#	And should be run manually on viola, as cyclestreets

### Stage 1 - general setup

# Ensure this script is NOT run as root (it should be run as cyclestreets)
if [ "$(id -u)" = "0" ]; then
    echo "#	This script must NOT be run as root." 1>&2
    exit 1
fi


# Bomb out if something goes wrong
set -e

### CREDENTIALS ###

# Get the script directory see: http://stackoverflow.com/a/246128/180733
# The multi-line method of geting the script directory is needed because this script is likely symlinked from cron
SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]
do 
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
SCRIPTDIRECTORY=$DIR

# Define the location of the credentials file relative to script directory
configFile=../.config.sh

# Generate your own credentials file by copying from .config.sh.template
if [ ! -x $SCRIPTDIRECTORY/${configFile} ]; then
    echo "# The config file, ${configFile}, does not exist or is not excutable - copy your own based on the ${configFile}.template file." 1>&2
    exit 1
fi

# Load the credentials
. $SCRIPTDIRECTORY/${configFile}

# Logging
setupLogFile=$SCRIPTDIRECTORY/log.txt
touch ${setupLogFile}
echo "#	CycleStreets fromOlivia in progress, follow log file with: tail -f ${setupLogFile}"
echo "$(date)	CycleStreets fromOlivia $(id)" >> ${setupLogFile}


#	Download and restore the CycleStreets database.
#	Folder locations
server=olivia.cyclestreets.net
folder=/websites/www/backups
download=${SCRIPTDIRECTORY}/../utility/downloadDumpAndMd5.sh

#	Download CyclesStreets Schema
$download $administratorEmail $server $folder olivia_schema_cyclestreets.sql.gz

#	Download & Restore CycleStreets database
$download $administratorEmail $server $folder olivia_cyclestreets.sql.gz

mysql -hlocalhost -uroot -p${mysqlRootPassword} -e "drop database if exists cyclestreets;";
mysql -hlocalhost -uroot -p${mysqlRootPassword} -e "create database cyclestreets default character set utf8 collate utf8_unicode_ci;";
gunzip < /websites/www/backups/olivia_cyclestreets.sql.gz | mysql -hlocalhost -uroot -p${mysqlRootPassword} cyclestreets

#	Stop duplicated cronning from the backup machine
mysql cyclestreets -hlocalhost -uroot -p${mysqlRootPassword} -e "update map_config set pseudoCron = null;";

#	Sync the photomap
sudo -u cyclestreets rsync -rt --cvs-exclude ${server}:${websitesContentFolder}/data/photomap ${websitesContentFolder}/data
sudo -u cyclestreets rsync -rt --cvs-exclude ${server}:${websitesContentFolder}/data/photomap2 ${websitesContentFolder}/data

#	Synchronization photos
sudo -u cyclestreets rsync -rt --cvs-exclude ${server}:${websitesContentFolder}/data/synchronization ${websitesContentFolder}/data

#	Latest routes
batchRoutes='olivia_routes_*.sql.gz'

#	Find all route files with the named pattern that have been modified within the last 24 hours.
files=$(ssh ${server} "find ${folder} -maxdepth 1 -name '${batchRoutes}' -type f -mtime 0 -print")
for f in $files
do
    #	Get only the name component
    fileName=$(basename $f)

    #	Get the latest copy of www's current IJS tables.
    $download $administratorEmail $server $folder $fileName

    #	Add them
    gunzip < /websites/www/backups/$fileName | mysql -hlocalhost -uroot -p${mysqlRootPassword} cyclestreets
done


#
#	Repartition, which copies the current to the archived tables, and log output.
mysql cyclestreets -hlocalhost -uroot -p${mysqlRootPassword} -e "call repartitionIJS()" >> ${setupLogFile}


#	CycleStreets Blog
$download $administratorEmail $server $folder olivia_schema_blog_database.sql.gz
mysql cyclestreets -hlocalhost -uroot -p${mysqlRootPassword} -e "drop database if exists blog;";
mysql cyclestreets -hlocalhost -uroot -p${mysqlRootPassword} -e "CREATE DATABASE blog DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;";
gunzip < /websites/www/backups/olivia_schema_blog_database.sql.gz | mysql -hlocalhost -uroot -p${mysqlRootPassword} blog

#	Cyclescape Blog
$download $administratorEmail $server $folder olivia_schema_blogcyclescape_database.sql.gz
mysql cyclestreets -hlocalhost -uroot -p${mysqlRootPassword} -e "drop database if exists blogcyclescape;";
mysql cyclestreets -hlocalhost -uroot -p${mysqlRootPassword} -e "CREATE DATABASE blogcyclescape DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;";
gunzip < /websites/www/backups/olivia_schema_blogcyclescape_database.sql.gz | mysql -hlocalhost -uroot -p${mysqlRootPassword} blogcyclescape

# End of file